"""empty message

Revision ID: 155487fd2547
Revises: c49a07b9e55b
Create Date: 2021-04-22 04:01:31.469166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155487fd2547'
down_revision = 'c49a07b9e55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', sa.String(length=50), nullable=True))
    op.add_column('planets', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'image')
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###
